version: '3'

services:
    # Start messaging broker
    rabbitmq:
        image: arm32v7/rabbitmq:3.6.15-management
        ports:
            - "5672:5672"
            - "15672:15672" #Management Server
        environment:
            RABBITMQ_DEFAULT_USER: "admin"
            RABBITMQ_DEFAULT_PASS: "Phaish9ohbaidei6oole"
        networks:
            - ocrnet

    # Start transformation worker
    strokewidthtransform:
        image: mysmartbus/open-ocr-preprocessor-arm32v7
        volumes:
            - ./scripts/:/opt/open-ocr/
        depends_on:
            - rabbitmq
        command: "/opt/open-ocr/open-ocr-preprocessor -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/ -preprocessor stroke-width-transform"
        networks:
            - ocrnet

    # Start OCR worker
    openocrworker:
        image: mysmartbus/open-ocr-arm32v7
        volumes:
            - ./scripts/:/opt/open-ocr/
        depends_on:
            - rabbitmq
        command: "/opt/open-ocr/open-ocr-worker -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/"
        networks:
            - ocrnet

    # Start http server
    openocr:
        image: mysmartbus/open-ocr-arm32v7
        volumes:
            - ./scripts/:/opt/open-ocr/
        ports:
            - "9292:9292"
        depends_on:
            - rabbitmq
            - openocrworker
            - strokewidthtransform
        command: "/opt/open-ocr/open-ocr-httpd -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/ -http_port 9292"
        networks:
            - ocrnet


networks:
    ocrnet:
        driver: overlay
